- name: create ec2 and route53 records
  hosts: all
  connection: local
  vars:
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sg-051e7eba9b20c046f
    env: dev
    instances:
    - mongodb
    - catalogue
    - frontend
    domain_name: srikanthchalla.online
    action: create
  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        instance_type: "t3.micro"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        name: "{{ item }}-{{ env }}"
        tags:
          project: roboshop
          Component: "{{ item }}"
          Environment: "{{ env }}"
          Name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
      register: ec2_output
      when: action == "create"
      ignore_errors: true

    - name: print the output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"
      when: action == "create"
      
    - name: create r53 records
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}-{{ env }}.{{ domain_name }}" # mongodb-dev.daws88s.online, frontend-dev.daws88s.online
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        wait: true
      loop: "{{ ec2_output.results }}" # list


    - name: create r53 records for fronten
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "roboshop-{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        wait: true
      loop: "{{ ec2_output.results }}" # list
      when: item.item == "frontend"
        msg: "{{ ec2_output }}"
        
        ### DESTROY ###
    - name:
      amazon.aws.route53:
        state: absent
        zone: "{{ domain_name }}"
        record: "{{ item }}-{{ env }}.{{ domain_name }}" # roboshop-dev.daws88s.online
        type: A
        ttl: 1
      loop: "{{ instances }}"
      when: action == "destroy"


    - name: delete ec2 instance
      amazon.aws.ec2_instance:
        state: absent
        name: "{{ item }}-{{ env }}"
        wait: false
      loop: "{{ instances }}"
      when: action == "destroy"



  u
